# Site settings
title: Thank you
email: helloworld_1620@naver.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml.
baseurl: "/teacher" # the subpath of your site, e.g. /blog/
url: "https://thx-day.github.io" # the base hostname & protocol for your site
twitter_username: null
github_username:  null

# Build settings
markdown: kramdown
